"use strict";
const assert = require("node:assert/strict");
const Tree = require("../field/tree-identification-engine.js");
const inspection = { inspection_id: "I-1", property_id: "Property-00000017", tree_identification_sessions: [] };
const gps = { latitude: 30.49, longitude: -87.09, accuracy_m: 5, recorded_at: "2026-08-04T12:00:00Z" };
const first = Tree.createSession(inspection, { feature_capture_session_id: "F-1", tree_observation_id: "O-1", phone_gps: gps });
const second = Tree.createSession(inspection, { feature_capture_session_id: "F-2", tree_observation_id: "O-2", phone_gps: gps });
assert.equal(first.tree_identifier, "TREE-001"); assert.equal(second.tree_identifier, "TREE-002"); assert.notEqual(first.tree_id, second.tree_id);
const m = Tree.recordCircumference(inspection, first.tree_identification_session_id, { original_circumference_value: 62.5, original_circumference_unit: "in", circumference_tool: "FLEXIBLE_HOSPITAL_TAPE", measurement_classification: "Measured", measurement_height: 54, measurement_height_unit: "in", measurement_height_basis: "UPHILL_SIDE" });
assert.equal(m.original_circumference_value, 62.5); assert(Math.abs(m.calculation.exact_calculated_dbh_original_unit - 62.5 / Math.PI) < 1e-12); assert(Math.abs(m.calculation.exact_calculated_radius_original_unit - 62.5 / (2 * Math.PI)) < 1e-12); assert.match(m.calculation.classification, /NOT_DIRECTLY_MEASURED/);
const direct = Tree.recordDirectDiameter(inspection, second.tree_identification_session_id, { original_diameter_value: 18, original_diameter_unit: "in", measurement_method: "Diameter tape", measurement_classification: "Measured", measurement_height: 54, measurement_height_unit: "in", measurement_height_basis: "UPHILL_SIDE" }); assert.equal(direct.directly_measured_diameter, true); assert.equal(direct.original_diameter_value, 18);
Tree.attachDirectMedia(inspection, first.tree_identification_session_id, { media_id: "P1", media_role: "Bark close-up", original_file_hash: "a".repeat(64), material_association: "ATTACHED_TO_TARGET_TREE" });
Tree.attachDirectMedia(inspection, first.tree_identification_session_id, { media_id: "P2", media_role: "Leaf attached to twig", original_file_hash: "b".repeat(64), material_association: "FOUND_IN_MIXED_GROUND_MATERIAL" });
assert.equal(first.direct_media_relationships[0].source_relationship_status, "DIRECT_AT_CAPTURE"); assert.equal(first.direct_media_relationships[1].association_proves_target_material, false);
Tree.markEvidenceUnavailable(inspection, first.tree_identification_session_id, "Whole tree", "Dense vegetation", "Canopy and adjacent trunks block a safe full view.");
Tree.markEvidenceUnavailable(inspection, first.tree_identification_session_id, "Crown", "Dense vegetation");
Tree.saveMinimum(inspection, first.tree_identification_session_id);
assert.equal(first.session_status, "MINIMUM_EVIDENCE_CAPTURED");
const original = JSON.stringify({ id: "legacy-tree", type: "tree" }); const legacy = JSON.parse(original); inspection.markers = [legacy]; Tree.ensureModel(inspection); assert.equal(JSON.stringify(inspection.markers[0]), original);
assert.throws(() => Tree.attachDirectMedia(inspection, second.tree_identification_session_id, { media_id: "P3" }), /hash/);
process.stdout.write("PASS: unique tree IDs, circumference provenance, direct media, association limits, adaptive unavailable evidence, and non-destructive legacy handling.\n");
