const assert=require("assert");
const fs=require("fs");
const path=require("path");
const root=path.join(__dirname,"..","property-production-intelligence-test");
const read=(name)=>fs.readFileSync(path.join(root,name),"utf8");
const files=["index.html","app.js","styles.css","production-engine-core.js","sw.js","manifest.webmanifest","DEPLOYMENT_IDENTITY.json","README.md"];
files.forEach((file)=>assert(fs.existsSync(path.join(root,file)),`missing ${file}`));
const html=read("index.html"),app=read("app.js"),sw=read("sw.js"),all=files.map(read).join("\n");
assert(html.includes("ISOLATED PRODUCTION INTELLIGENCE TEST"));
assert(html.includes("9a6e8e070c3cec1437ee3c8a74342edf4cbe6575"));
assert(html.includes("PREPARING OFFLINE STORAGE"));
assert(app.includes('property-production-intelligence-poc-v1'));
assert(sw.includes('property-production-intelligence-poc-v1-cache-9a6e8e0'));
assert(sw.includes('new URL(self.registration.scope).pathname'),"fetch handling must stay within the isolated service-worker scope");
assert(!all.match(/Pearson/i),"public runtime must not contain Pearson property information");
assert(!all.match(/-87\.\d{3,}/),"public runtime must not contain precise longitude-like Pearson coordinates");
assert(!all.match(/30\.\d{3,}/),"public runtime must not contain precise latitude-like Pearson coordinates");
assert(!all.match(/\.(jpe?g|heic|png)/i),"public runtime must not include property photograph references");
assert(!app.includes("propertyInspectorHomeTest313V1"));
assert(!app.includes("property-inspector-home-test-313-evidence"));
assert(app.includes("saved_tests"),"multiple offline production tests must remain saved");
console.log("production-intelligence-public-deployment.test.js passed");
